phonlab-tcd/An-Scealai

api/routes/recording.route.js, api/routes/story.route.js, src/app/recording.service.ts, src/app/student-components/recording-history/recording-history.component.css, src/app/student-components/recording-history/recording-history.component.html, src/app/student-components/recording-history/recording-history.component.ts, src/app/student-components/recording/recording.component.html, src/app/student-components/recording/recording.component.ts, src/app/student-components/view-recording/view-recording.component.html
Show each previous recording and their data.  When a recording is clicked, direct to view-recording component.
=> List of previous recordings

src/app/student-components/recording/recording.component.css, src/app/student-components/recording/recording.component.html, src/app/student-components/recording/recording.component.ts
=> Archive Button CSS

src/app/app-routing.module.ts, src/app/can-deactivate.guard.ts, src/app/student-components/recording/recording.component.css, src/app/student-components/recording/recording.component.html, src/app/student-components/recording/recording.component.ts
- Added modal popup box to recording page to prevent people leaving without the option to save.
**Looks like this:**
**Sidenote:** @NeasaNi we'll get a list of translations for you soon (there are probably a few hard-coded English words around the new recording components). @maddiecomtois there may be some in the recording history too?
=> Recording Saving Modal Popup

api/routes/story.route.js, src/app/student-components/dashboard/dashboard.component.ts
- All grammar errors should be checked by default now.
=> Grammar errors all checked

api/models/recording.js, api/routes/recording.route.js, src/app/recording.service.ts, src/app/recording.ts, src/app/student-components/recording-history/recording-history.component.html, src/app/student-components/recording-history/recording-history.component.ts, src/app/student-components/recording/recording.component.html, src/app/student-components/recording/recording.component.ts, src/app/student-components/view-recording/view-recording.component.css, src/app/student-components/view-recording/view-recording.component.html, src/app/translation.json
Did not get to deleting disconnected audio, have the code commented out for now.  In the meantime added translations and other small functionality.
=> updated translations and save features

src/app/student-components/recording/recording.component.ts
- Fixes recording duplication at first recording session. The problem was that synthesiseStory() was being called twice, quick fix (:
=> Recording duplication fix

deploy.sh
* Added script `deploy.sh` which should run all commands necessary to update the live server with the latest code on the GitHub master branch.
=> Added auto-deploy script

src/app/admin-components/story/story.component.ts, src/app/admin-components/teachers/teachers.component.ts, src/app/admin-components/user/user.component.ts, src/app/teacher-components/teacher-story/teacher-story.component.ts
- Replaces hardcoded `localhost` backend url with pointers to `abairconfig.baseurl` variable, which is updated by the deploy script. This way only `abairconfig.baseurl` needs to be changed in order to update the backend base URL for the site.
=> Removed hardcoded backend urls

api/routes/story.route.js, src/app/services/synthesis.service.ts, src/app/student-components/recording/recording.component.css, src/app/student-components/recording/recording.component.html, src/app/student-components/recording/recording.component.ts, src/app/student-components/synthesis/synthesis.component.ts, src/app/teacher-components/teacher-dashboard/teacher-dashboard.component.ts
* Replaced copy/pasted synthesis code with new synthesis service code to avoid code repetition.
* Makes the file slightly more readable by reducing amount of functions that aren't directly relevant to that component.
* `recording.component.ts` still implements its own audio recording and playback, which should probably be packaged in its own service as audio recording & playback is used elsewhere on the site.
=> Using synthesis service on recording page

deploy.sh
* _tiny_ PR updating the `deploy` script to install node modules after pulling.
=> Updated deploy script to install dependencies

LICENSE
Adding GPL licence to An Scéalaí repository, as discussed with TCD
=> GNU GENERAL PUBLIC LICENSE

api/models/story.js, api/routes/recording.route.js, api/routes/story.route.js, api/routes/studentStats.route.js, ngapp/src/app/admin-components/story/story.component.css, ngapp/src/app/app.component.html, ngapp/src/app/grammar.service.ts, ngapp/src/app/story.service.ts, ngapp/src/app/story.ts, ngapp/src/app/student-components/book-contents/book-contents.component.html, ngapp/src/app/student-components/dashboard/dashboard.component.html, ngapp/src/app/student-components/dashboard/dashboard.component.ts, ngapp/src/app/student-components/new-story/new-story.component.ts, ngapp/src/app/student-components/recording/recording.component.html, ngapp/src/app/student-components/recording/recording.component.ts, ngapp/src/app/student-components/story-details/story-details.component.html, ngapp/src/app/student-components/story-details/story-details.component.ts, ngapp/src/app/student-components/view-recording/view-recording.component.html
Deleted all instances of 'id' and replace calls to story with '_id'.
Added studentId to story object
=> get rid of 'id'

ngapp/src/app/student-components/dashboard/dashboard.component.html
Moved the wordcount div to after all the conditional divs which stops it form disappearing.
=> fix wordcount to one location

api/routes/user.route.js, ngapp/src/app/profile/profile.component.ts, ngapp/src/app/translation.json
Post error message if user tries to update their username to one with spaces and/or special characters
=> check username for spaces/characters

api/controllers/authentication.js
Same thing as before but this is a branch of master.
Swap findOneAndUpdate() for findOne() and save()
=> swap .findOneAndUpdate() to findOne()  and save()

api/routes/studentStats.route.js
Update username code for studentStats repeated in the backend, might have been caused by a merge.
Code still worked for me locally anyway, but it's not working on the server.  Maybe this will fix it?
=> delete repeated code

ngapp/package-lock.json, ngapp/package.json, ngapp/src/app/grammar.service.ts, ngapp/src/app/story.service.ts, ngapp/src/app/student-components/dashboard/dashboard.component.css, ngapp/src/app/student-components/dashboard/dashboard.component.html, ngapp/src/app/student-components/dashboard/dashboard.component.ts
This was my first attempt to toggle the grammar tags.
I have a feeling there are still bugs and redundancy, just want people to know it's here.
Still definitely needs to be tidied up before merging.
=> Quill highlight toggle grammar tag visibility

ngapp/src/app/resources/resources.component.html
- add dialects nnc and anb for An Prionsa Beag
=> Update LARA links

spinup.bash
I think I'm the only person who uses this rn so I'm just gonna merge.
=> better spinup.sh

ngapp/src/app/resources/resources.component.html
Update the links to the LARA stories with their new location
=> Lara link update

ngapp/src/app/app.component.css, ngapp/src/app/app.component.html
With all the things in the navbar the text sometimes overlaps!
Changing max-width css rule to 1150px so that the text fits!
=> max-width to 1150px and reformat html source

api/endpoints_functions/story/feedbackAudio.js, api/endpoints_functions/story/getStoryById.js, api/endpoints_functions/user/searchUser.js, api/globalConfig.json, api/package.json, api/routes/messages.route.js, api/routes/recording.route.js, api/routes/story.route.js, api/routes/story.route.test.js, api/routes/user.route.test.js
- comment out some unnecessary db connections (PLEASE CHECK THIS IS OK!)
- update some tests
- create test_silent script (suppress console.logs in test)
- sort array of users alphabetically before expecting username values in
user test
=> Some additions

api/routes/user.route.js, ngapp/src/app/user.service.ts
Hello,
It appears the `/getAllUsers` endpoint is not used anywhere in the code.
It also happens to be very problematic (PM me for details). It should be removed ASAP.
I will merge and push this on Saturday, unless there are objections.
=> kill getAllUsers endpoint

ngapp/src/app/prompts/prompts.component.html, ngapp/src/app/prompts/prompts.component.ts
- Some code refactored for DRYness, (`tempWordDatabase`)
- ng data binding of the SynthItem instance updated so as to not make unneccessary http requests, and to dispose of the unused 'synthItems'
- change `<li>` to `<p>`
=> Neimhin's edits of Fionn's POS prompts PR

api/endpoints_functions/gramadoir/insert.ts
Addresses #382 
* Currently just trying to catch this error and handle it appropriately so that we can get logs to analyse.
=> `gramadoir/insert` error handling

.gitignore
- added these lines to gitignore
```
ngapp/qa_build/**
ngapp/unpublished_dist/**
ngapp/coverage/**
```
=> Update .gitignore to ignore build files

ngapp/src/app/student/dashboard/dashboard.component.html, ngapp/src/app/student/dashboard/dashboard.component.scss
- added the word count back in
- Is this the best place to put it?
=> add word count

ngapp/src/app/student/dashboard/dashboard.component.scss, ngapp/src/lib/synth/buttons.ts
https://github.com/phonlab-tcd/An-Scealai/issues/490
Added a loading spinner that displays for the intermediate time between clicking the synth button and `audio.play()` being called.
Here's how it looks:
https://github.com/phonlab-tcd/An-Scealai/assets/34962541/1b585cd6-2cca-431e-87f6-3acf56e6cd2a
=> Adds loading spinner for TTS

ngapp/src/app/messages/messages.component.ts, ngapp/src/app/student/home-page/home-page.component.html, ngapp/src/app/student/home-page/home-page.component.scss, ngapp/src/app/student/home-page/home-page.component.spec.ts, ngapp/src/app/student/home-page/home-page.component.ts, ngapp/src/app/student/student-routing.module.ts, ngapp/src/app/student/student.module.ts, ngapp/src/app/translation.ts
- New home page that students see when they log in (also accessible by clicking the 'Home' button)
- Feedback on design?
- Will need translations for whatever content we want to put in the boxes (initial ideas there now)
- Do we get rid of the Apps menu at the top then?
=> App home page

ngapp/src/app/app.module.ts, ngapp/src/app/login/login.component.html, ngapp/src/app/login/login.component.scss, ngapp/src/app/login/login.component.ts
- 'sign in' button text replaced with loading spinner until user is redirected to home page
=> add loading spinner for login

ngapp/src/app/core/services/auth-guard.service.ts, ngapp/src/app/login/login.component.ts, ngapp/src/app/student/dashboard/dashboard.component.html, ngapp/src/app/student/dashboard/dashboard.component.ts, ngapp/src/lib/grammar-engine/checkers/an-gramadoir.ts, ngapp/src/lib/quill-highlight/quill-highlight.ts
- Added a check in the an gramadoir code to see if the user's computer has enough memory to import the TS Grammar checker
- If the user does, they load in the TS grammar checker and proceed as normal (which seemed to be working ok for the majority of people)
- If the user does not have enough memory, the grammar checker now works by making API calls to An Gramadoir that we are currently serving at gramadoir.abair.ie. 
- This PR contains additional small, unrelated improvements: no spell check with quill, better grammar tag error handling, etc.
=> An Gramadoir memory check

api/src/endpoint/feedback/getFeedbackStats.ts, api/src/endpoint/story/getStoryStats.ts, api/src/endpoint/user/countAndStatus.ts, api/src/routes/classroom.route.js, api/src/routes/feedbackComment.route.ts, ngapp/src/app/admin/admin-dashboard/admin-dashboard.component.html, ngapp/src/app/admin/database-stats/database-stats.component.html, ngapp/src/app/admin/database-stats/database-stats.component.ts, ngapp/src/app/admin/find-user/find-user.component.html, ngapp/src/app/core/services/classroom.service.ts, ngapp/src/app/core/services/feedback-comment.service.ts
- stats no longer crash
- clean up of older code
- todo: update the way we store grammar error counts and reflect this data to the dashboard
=> Refactor admin db stats
